version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - PORT=3000
      - UPLOAD_DIR=/app/public/uploads
      - DATABASE_FILE=/app/data/invoices.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_FILE=/app/data/invoices.db
    volumes:
      - ..:/app
    command: ["node", "src/queue/worker.js"]
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
